  name: Day Challenge
  run-name: Running Day Challenge 🚀
  on: [push]
  jobs:
    Day-Challenge-Actions:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@v3

        - name: install python
          run: |
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip

        - name: install ansible-lint and yamllint
          run: |
            pip3 install ansible-lint 
            pip3 install yamllint

        - name: run yaml lint
          run: |
            find . -name "*.yml" -print0 | xargs -0 yamllint

        - name: ansible lint 
          run: |
            find . -name "*.yml" -print0 | xargs -0 ansible-lint
